name: Lint
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install ESLint dependencies
        run: |
          cd .github/linting
          npm install
      - name: Run ESLint
        run: npx eslint .
